---
layout: post
title: Picking a gui interface for R
tags: [R, gui]
---

Recently I decided to switch statistical programs used for the master's level introductory statistics course I teach here at the University of Arkansas.  Historically this course has been taught with SPSS, but I am attempting the switch to R this semester.  

My reasons for having students use the gui interface is primarily due to the lack of programming experience.  A brief initial poll revealed that only one student had prior programming/code writing experience.  Therefore, I did not want to have students become acclimated to the statistics content as well as the R code.  The two primary gui systems/packages I explored were the *Deducer* package and *Rcmdr* package.  Here are my initial thoughts on the switch.

### Which gui to use?
This ultimately comes down to personal preference, however below I've highlighted my thoughts on pros/cons of each package.

Deducer   
=========
| Pros                             | Cons                             |   
|----------------------------------|----------------------------------|
| Shows syntax of commands run     | Uses Java                        |  
| Uses ggplot2 for plots           | Menus differ from PC to MAC      |  
| Very interactive menu structures | rJava package can be troublesome |   
| Simple condensed data loading    |                                  |  

Rcmdr
========
| Pros                              | Cons                             |   
|-----------------------------------|----------------------------------|
| Shows syntax of commands run      | Uses base graphics               |  
| Does not use Java                 | Data loading structures not integrated |  
| Very similar data menus across OS |   | 

In general I prefer the *Deducer* package as it uses ggplot2 and has a more unified menu structure.  For example, there are not differing menu options for loading data like in *Rcmdr*.  Instead, *Deducer* has a single load data menu where it is possible to load many types of data including csv, txt, rda, etc.  This is helpful for students who are not very familiar with differing file types.  *Deducer* also uses ggplot2 for its graphics which I enjoy much more than base graphics.  In my opinion they look better and the syntax is ultimately easier to create high quality graphics.

My biggest complaint of the *Deducer* package is that it uses Java.  This is one more thing that the user needs to install and with my class we have had trouble on a few computers getting the *rJava* package to work properly.  In general it is difficult to troubleshoot a student's computer, especially when I am unable to recreate the problem on my own machine.  Lastly, the differing look of *Deducer* has made it more difficult for me as I need to have two explanations, one for those on a PC and another for those on a Mac.  Just tedious and has been difficult for me as I do not use Mac.

### Concluding thoughts
I hope to write more about my experiences using both gui systems for my class, but upon initial inspection of them now I definitely prefer *Deducer*.  The package just has not completely won me over as little problems have made me use both packages in my class so far.  Does anyone else have experience using one or the other in a class before?  I'd enjoy hearing any stories using these or different gui systems for R.
